server:
  port: 8080
spring:
  application:
    name: marketing
---

spring:
  profiles: default
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://${_DATASOURCE_ADDRESS:localhost:3306}/${_DATASOURCE_TABLESPACE:my-database}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${_DATASOURCE_USERNAME:root}
    password: ${_DATASOURCE_PASSWORD:1234}
    driverClassName: com.mysql.cj.jdbc.Driver       
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: marketing
          destination: kafka.cdc
          contentType: application/json
        event-out:
          destination: kafka.cdc
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

api:
  url:
    marketing: marketing:8082


server:
  port: 8082

---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: marketing
          destination: kafka.cdc
          contentType: application/json
        event-out:
          destination: kafka.cdc
          contentType: application/json

api:
  url:
    marketing: marketing:8080


